### ISSUE TITLE
Unable to build on Win64

### ISSUE THREAD

**Issue by BNNorman** [menpo/conda-opencv#4]
Trying to build with FFMPEG support for Anaconda2 on quad core Dell Inspiron 64 Bit running Windows 10. Have edited the build.sh and bld.bat files to set FFMPEG flags to 1. I did update conda and conda build plus installed cmake and git before running the 'conda build conda.' command

I don't know what needs installing to solve the unsatisfiable dependencies for win-64. The only thing I can say is the _test_env and _h_env mentioned before the traceback are not present. The win-64 folder contains some json files but they only contain "{}" with the exception of repodata.json which contains this :-
{
  "info": {
    "subdir": "win-64"
  },
  "packages": {}
}

Please can you advise. 
Many Thanks.

Conda build output is as follows:-

c:\ProgramData\Anaconda2\Scripts\conda-opencv>..\conda build conda
Attempting to finalize metadata for opencv
INFO:conda_build.metadata:Attempting to finalize metadata for opencv

Leaving build/test directories:
  Work:  c:\ProgramData\Anaconda2\conda-bld\work
  Test:  c:\ProgramData\Anaconda2\conda-bld\test_tmp
Leaving build/test environments:
  Test: source activate  c:\ProgramData\Anaconda2\conda-bld\_test_env
  Build:        source activate  c:\ProgramData\Anaconda2\conda-bld\_h_env

Traceback (most recent call last):
  File "c:\ProgramData\Anaconda2\Scripts\conda-build-script.py", line 10, in <module>
    sys.exit(main())
  File "c:\ProgramData\Anaconda2\lib\site-packages\conda_build\cli\main_build.py", line 388, in main
    execute(sys.argv[1:])
  File "c:\ProgramData\Anaconda2\lib\site-packages\conda_build\cli\main_build.py", line 379, in execute
    verify=args.verify)
  File "c:\ProgramData\Anaconda2\lib\site-packages\conda_build\api.py", line 187, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "c:\ProgramData\Anaconda2\lib\site-packages\conda_build\build.py", line 1802, in build_tree
    notest=notest,
  File "c:\ProgramData\Anaconda2\lib\site-packages\conda_build\build.py", line 895, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "c:\ProgramData\Anaconda2\lib\site-packages\conda_build\render.py", line 582, in expand_outputs
    for (output_dict, m) in _m.get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "c:\ProgramData\Anaconda2\lib\site-packages\conda_build\metadata.py", line 1788, in get_output_metadata_set
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "c:\ProgramData\Anaconda2\lib\site-packages\conda_build\metadata.py", line 648, in finalize_outputs_pass
    fm = finalize_metadata(om, permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "c:\ProgramData\Anaconda2\lib\site-packages\conda_build\render.py", line 314, in finalize_metadata
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "c:\ProgramData\Anaconda2\lib\site-packages\conda_build\render.py", line 115, in get_env_dependencies
    channel_urls=tuple(m.config.channel_urls))
  File "c:\ProgramData\Anaconda2\lib\site-packages\conda_build\environ.py", line 687, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform win-64: set(['cmake 3.3.0.*'])

c:\ProgramData\Anaconda2\Scripts\conda-opencv>

**Comment by BNNorman** [comment]
I have a workaround - so not very urgent
Some time ago I compiled openCV for windows. I copied the 64 bit cv2.pyd file from the build/python/2.7 folder and replaced the Anaconda2 version in site-packages and it works ok.
Nevertheless, it would be nice if conda build worked and I'm still curious as to why not.
